### ISSUE TITLE
make a php Importer page from a local db3 file to server database

### ISSUE THREAD

**Issue by avs-code** [avs-code/PREM-Podium-race-E-manager#34]
Import data from Stracker database sqlite file to PREM database.

**Comment by stmeissner** [comment]
@arv187 Could you please explain how this should work in detail?
According to [sTracker docs]() reading from sqlite would require sTracker and PREM to run on the same server:
`One of the limitations of sqlite is that you cannot access this database accross computers. Storing the .db3 file on a network share will not work. `
That's why sTracker has a network interface around the database, which exposes the data to pTracker.
From what I know sTracker provides live data mainly, not sure this is the best solution for PREM where you are mostly interested in the final results of session, aren't you?

**Comment by avs-code** [comment]
This was a Wolfgang's petition, to import his previous championships data from stracker.
You can transform a sqlite to mysql and with a intermediate file get fields to put data in new database but seems encrypted or corrupted. May be best edit database at hand.

[stracker_sql.zip](https://github.com/arv187/PREM-Podium-race-E-manager/files/1052770/stracker_sql.zip)
